os: windows
language: sh

py35-steps: &py34-steps
  env: PATH=/c/Python34:/c/Python34/Scripts:$PATH
  before_install:
    - choco install python --version 3.4
    - python -m pip install --upgrade pip

matrix:
  allow_failures:
    - python: 3.4
  include:
    - name: "Python 3.4: Run tests"
      <<: *py34-steps

deploy:
  provider: releases
  api_key: ${api_key}
  file_glob: true
  file: distrib/*
  skip_cleanup: true
  draft: true
  on:
    all_branches: true
    tags: false

install:
 - pip install cx_freeze==4.3.3
 - pip install libyaz0
 - pip install sarclib
 - pip install pyqt5
 - pip install sip

script:
  - py build.py
