os: windows
language: shell
name: "Python 3.8.0 on Windows"
before_install:
  - choco install python --version 3.8.0
  - python -m pip install --upgrade pip

env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install: 


virtualenv:
  system_site_packages: true

install:
  - pip3 install --upgrade pip
  - pip install libyaz0
  - pip install sarclib
  - pip install pyqt5
  - pip install sip
  - pip install cx_freeze
  - pip install --user sip
  - pip install -U --user PyQt5 PyQt5_sip
  - pip install --upgrade --force-reinstall pyqt5;
  
deploy:
  provider: releases
  api_key: ${api_key}
  file_glob: true
  file: distrib/*
  skip_cleanup: true
  draft: true
  on:
    all_branches: true
    tags: false


script:
  - py build.py
