name: "Python 3.8.0 on Windows"
os: windows           # Windows 10.0.17134 N/A Build 17134
language: shell       # 'language: python' is an error on Travis CI Windows
before_install:
 - choco install python --version 3.8.0
 - python -m pip install --upgrade pip
env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

deploy:
  provider: releases
  api_key: ${api_key}
  file_glob: true
  file: distrib/*
  skip_cleanup: true
  draft: false
  on:
    all_branches: true
tags: false

install:
 - pip3 install --upgrade pip
 - pip install cx_freeze
 - pip install libyaz0
 - pip install sarclib
 - pip install pyqt5
 - pip install sip
script:
  - py build.py
