language: python
python:
 - "3.4"

install:
  - "pip install cx_freeze==4.3.3"
  - "pip install https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.4.1/PyQt-gpl-5.4.1.tar.gz/download"
script: 
  - python build.py