os: windows
language: sh

py37-steps: &py37-steps
  env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
  before_install:
    - choco install python --version 3.7
    - python -m pip install --upgrade pip

matrix:
  allow_failures:
    - python: 3.7  # f-strings are available on Python >= 3.6
  include:
    - name: "Python 3.5: Run tests"
      <<: *py35-steps

deploy:
  provider: releases
  api_key: ${api_key}
  file_glob: true
  file: distrib/*
  skip_cleanup: true
  draft: true
  on:
    all_branches: true
    tags: false

install:
 - pip install cx_freeze
 - pip install libyaz0
 - pip install sarclib
 - pip install pyqt5
 - pip install sip
 - pip install Cython

script:
  - py build.py
