os: windows
language: sh

py35-steps: &py35-steps
  env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
  before_install:
    - choco install python --version 3.5.4
    - python -m pip install --upgrade pip

