language: python
sudo: required
dist: trusty

python:
  - "2.7"
  - "3.4"

virtualenv:
  system_site_packages: true

install:
 - "pip install cx_freeze==4.3.3"
 - sudo apt-get update
 - sudo apt-get -y install python3-pyqt5