on: [push]

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.7]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install PyQt5 libyaz0 SarcLib cx_freeze Cython PyQt5-sip
    - name: Build 
      run: |
        python -OO build.py
    - name: Tar (Linux/Mac)
      run: |
        cd distrib
        tar -czvf ../build-${{ matrix.platform }}.tar.gz ./*
        cd ..
      if: ${{ matrix.platform == 'macos-latest' || matrix.platform == 'ubuntu-latest' }}
    - name: Upload artifacts (Linux/Mac)
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.platform }}
        path: build-${{ matrix.platform }}.tar.gz
      if: ${{ matrix.platform == 'macos-latest' || matrix.platform == 'ubuntu-latest' }}
    - name: Upload artifacts (Win)
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.platform }}
        path: distrib/*
      if: ${{ matrix.platform == 'windows-latest' }}
